version: "3.9"

services:
  db:
    image: postgres:16
    container_name: contact_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: contact_list
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: contact_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:secret123@db:5432/contact_list
      JWT_SECRET: supersecretkey123
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  db_data:
